version: '3'

services:
  login_app:
    build:
      context: ./authentication
    ports:
      - "8081:8081"
      
  resource_util_app:
    build:
      context: ./resource-util
    ports:
      - "8082:8082"