name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    environment: Docker

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for authentication app
      run: docker build . --file authentication/Dockerfile --tag campionulclujului/auth-app-github:latest
    - name: Build the Docker image for resource util app
      run: docker build . --file resource-util/Dockerfile --tag campionulclujului/resource-app-github:latest
    - name: Login Docker Hub
      run: |
        echo "DOCKER_USERNAME: $DOCKER_USERNAME"
        echo "DOCKER_PASSWORD: $DOCKER_PASSWORD" 
        docker login -p $DOCKER_PASSWORD -u $DOCKER_USERNAME
    - name: Push authentication app
      run: docker push campionulclujului/auth-app-github:latest
    - name: Push resource util app
      run: docker push campionulclujului/resource-app-github:latest
